// <auto-generated />
using System;
using CarlosCustodio_Ap1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarlosCustodio_Ap1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241118230230_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarlosCustodio_Ap1_P2.Models.ArticulosC", b =>
                {
                    b.Property<int>("articuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("articuloId"));

                    b.Property<decimal>("costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("existencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("articuloId");

                    b.ToTable("ArticulosC");

                    b.HasData(
                        new
                        {
                            articuloId = 1,
                            costo = 2500.00m,
                            descripcion = "RAM Corsair 16GB",
                            existencia = 100m,
                            precio = 5000.00m
                        },
                        new
                        {
                            articuloId = 2,
                            costo = 1500.00m,
                            descripcion = "Disco Duro HP 524GB",
                            existencia = 100m,
                            precio = 3000.00m
                        },
                        new
                        {
                            articuloId = 3,
                            costo = 15000.00m,
                            descripcion = "Intel i7 11va Gen",
                            existencia = 100m,
                            precio = 35000.00m
                        },
                        new
                        {
                            articuloId = 4,
                            costo = 3000.00m,
                            descripcion = "Power Suply Corsair",
                            existencia = 100m,
                            precio = 5000.00m
                        });
                });

            modelBuilder.Entity("CarlosCustodio_Ap1_P2.Models.Combos", b =>
                {
                    b.Property<int>("combosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("combosId"));

                    b.Property<decimal>("costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("vendido")
                        .HasColumnType("int");

                    b.HasKey("combosId");

                    b.ToTable("combo");
                });
#pragma warning restore 612, 618
        }
    }
}
